WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
{'train_file': '/root/P9D/train_500.json', 'test_file': '/root/P9D/test_500.json', 'query_file': '/root/P9D/test_500.json', 'gallery_file': '/root/P9D/test_500.json', 'train_image_root': '/root/P9D/train', 'test_image_root': '/root/P9D/test', 'gallery_image_root': '/root/P9D/test', 'vit': 'base', 'vit_grad_ckpt': False, 'vit_ckpt_layer': 0, 'image_size': 224, 'batch_size_train': 64, 'batch_size_test': 64, 'weight_decay': 0.05, 'init_lr': 3e-05, 'min_lr': 1e-06, 'k_test': 10, 'max_words': 30, 'window_size': 50, 'max_epoch': 100, 'task': ['食品/保健', '家居用品'], 'base_mode': 'seqF'}
{'train_file': '/root/P9D/train_500.json', 'test_file': '/root/P9D/test_500.json', 'query_file': '/root/P9D/test_500.json', 'gallery_file': '/root/P9D/test_500.json', 'train_image_root': '/root/P9D/train', 'test_image_root': '/root/P9D/test', 'gallery_image_root': '/root/P9D/test', 'vit': 'base', 'vit_grad_ckpt': False, 'vit_ckpt_layer': 0, 'image_size': 224, 'batch_size_train': 64, 'batch_size_test': 64, 'weight_decay': 0.05, 'init_lr': 3e-05, 'min_lr': 1e-06, 'k_test': 10, 'max_words': 30, 'window_size': 50, 'max_epoch': 100, 'task': ['食品/保健', '家居用品'], 'base_mode': 'seqF'}{'train_file': '/root/P9D/train_500.json', 'test_file': '/root/P9D/test_500.json', 'query_file': '/root/P9D/test_500.json', 'gallery_file': '/root/P9D/test_500.json', 'train_image_root': '/root/P9D/train', 'test_image_root': '/root/P9D/test', 'gallery_image_root': '/root/P9D/test', 'vit': 'base', 'vit_grad_ckpt': False, 'vit_ckpt_layer': 0, 'image_size': 224, 'batch_size_train': 64, 'batch_size_test': 64, 'weight_decay': 0.05, 'init_lr': 3e-05, 'min_lr': 1e-06, 'k_test': 10, 'max_words': 30, 'window_size': 50, 'max_epoch': 100, 'task': ['食品/保健', '家居用品'], 'base_mode': 'seqF'}
{'train_file': '/root/P9D/train_500.json', 'test_file': '/root/P9D/test_500.json', 'query_file': '/root/P9D/test_500.json', 'gallery_file': '/root/P9D/test_500.json', 'train_image_root': '/root/P9D/train', 'test_image_root': '/root/P9D/test', 'gallery_image_root': '/root/P9D/test', 'vit': 'base', 'vit_grad_ckpt': False, 'vit_ckpt_layer': 0, 'image_size': 224, 'batch_size_train': 64, 'batch_size_test': 64, 'weight_decay': 0.05, 'init_lr': 3e-05, 'min_lr': 1e-06, 'k_test': 10, 'max_words': 30, 'window_size': 50, 'max_epoch': 100, 'task': ['食品/保健', '家居用品'], 'base_mode': 'seqF'}

Traceback (most recent call last):
  File "train_LWF.py", line 266, in <module>
    utils.init_distributed_mode(args)     
  File "/root/CTP/train/../utils.py", line 302, in init_distributed_mode
    torch.cuda.set_device(args.gpu)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/torch/cuda/__init__.py", line 326, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Traceback (most recent call last):
  File "train_LWF.py", line 266, in <module>
    utils.init_distributed_mode(args)     
  File "/root/CTP/train/../utils.py", line 302, in init_distributed_mode
    torch.cuda.set_device(args.gpu)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/torch/cuda/__init__.py", line 326, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Traceback (most recent call last):
  File "train_LWF.py", line 266, in <module>
    utils.init_distributed_mode(args)     
  File "/root/CTP/train/../utils.py", line 302, in init_distributed_mode
    torch.cuda.set_device(args.gpu)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/torch/cuda/__init__.py", line 326, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
| distributed init (rank 0, word 4): env://
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 788 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 789) of binary: /usr/local/miniconda3/bin/python
Traceback (most recent call last):
  File "/usr/local/miniconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/miniconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/torch/distributed/run.py", line 766, in <module>
    main()
  File "/usr/local/miniconda3/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/usr/local/miniconda3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/miniconda3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_LWF.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-03-12_23:16:02
  host      : I1872ed153500901b66
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 790)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-03-12_23:16:02
  host      : I1872ed153500901b66
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 791)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-03-12_23:16:02
  host      : I1872ed153500901b66
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 789)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
